language: python
python:
 - "3.6"

install:
 - pip install pipenv
 - cd aw-research && pipenv install && cd ..  # this will install aw-core, aw-client, and other quantifiedme/aw-research dependencies
 - pipenv install

script:
 - sed -i 's/personal = True/personal = False/' 'QuantifiedMe - Dashboard.ipynb'  # Set personal = False, in case it was accidentally comitted with `personal = True`
 - pipenv run jupyter nbconvert 'QuantifiedMe - Dashboard.ipynb' --execute --ExecutePreprocessor.kernel_name=python3
 - ls -l *.html
 - sha256sum *.html
