language: python
python:
 - "3.6"

install:
 - pip install poetry
 - poetry install
# - cd aw-research && poetry install && cd ..  # this will install aw-core, aw-client, and other quantifiedme/aw-research dependencies

script:
 - sed -i 's/personal = True/personal = False/' 'notebooks/QuantifiedMe - Dashboard.ipynb'  # Set personal = False, in case it was accidentally comitted with `personal = True`
 - poetry run jupyter nbconvert 'notebooks/QuantifiedMe - Dashboard.ipynb' --execute --ExecutePreprocessor.kernel_name=python3
 - ls -l notebooks/*.html
 - sha256sum notebooks/*.html
