# This is an example configuration file. It should be placed in ~/.config/quantifiedme/config.toml (or equivalent for your operating system)
# For more info, read the README.

[me]
name = "john"

# Hours of next day to count as being part of the previous day (for past midnight shenanigans)
date_offset_hours = 5

[data]
habitbull = "~/Downloads/HabitBullData.csv"
location = "~/location"
oura = "~/Downloads/oura_2020-02-27T09-07-47.json"
categories = "~/categories.toml"  # categories.toml from aw-research

[data.smartertime_buckets]
example-hostname = '~/data/smartertime/smartertime_export_example-hostname_2020-01-01_bb7f26aa.awbucket.json'

[locations]

    [locations.gym]
    lat = 55.722379
    long = 13.213125
    accuracy = 0.001
