[tool.poetry]
name = "quantifiedme"
version = "0.1.0"
description = ""
authors = ["Erik Bjäreholt <erik@bjareho.lt>"]
license = "MPL-2.0"
packages = [
    { include = "quantifiedme", from = "src" },
]


[tool.poetry.dependencies]
python = "^3.8"
aw-core = "^0.5" 
aw-client = "^0.5" 
aw_research = {git = "https://github.com/ActivityWatch/aw-research.git"}
#aw_research = {path = "/home/erb/Programming/activitywatch/other/aw-research", develop=true}
qslang = {path = "./QSlang", develop=true}
numpy = "*"
scipy = "*"
#bottleneck = "1.2.3"
pandas = "*"
pandas-profiling = "^3.1"
matplotlib = "*"
#calmap = "*"
joblib = "*"
tabulate = "*"
pint = "*"
toml = "*"
togglcli = "^2.2"
#togglcli = {path = "vendor/toggl-cli"}
statsmodels = "^0.13.1"
types-click = "^0.1.14"
types-toml = "^0.1.1"
influxdb-client = {version = "^1.24.0", optional = true}

[tool.poetry.dev-dependencies]
jupyter = "^1.0.0"
ipykernel = "^5.1.3"
pytest = "^6.0"
pytest-cov = "*"
flake8 = "*"
mypy = "*"
jupyterlab = "*"
black = "*"
ipympl = "*"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "--cov=quantifiedme --cov-report=xml --cov-report=html --cov-report=term" # --profile --cov-report=term 
testpaths = [
    "src/quantifiedme",
    "tests",
]
python_files = ["*.py",]
filterwarnings = ["ignore::DeprecationWarning",]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
