[tool.poetry]
name = "quantifiedme"
version = "0.1.0"
description = ""
authors = ["Erik Bjäreholt <erik@bjareho.lt>"]
license = "MPL-2.0"

[tool.poetry.dependencies]
python = "^3.8"
numpy = "^1.18.0"
scipy = "^1.4.1"
pandas = "^0.25.3"
matplotlib = "^3.1.2"
calmap = "^0.0.7"
joblib = "^0.14.1"
qslang = {path = "QSlang"}
aw-research = {path = "aw-research"}
tabulate = "^0.8.6"
pint = "^0.9"
toml = "^0.10.0"
pytz = "^2019.3"
aw_core = {path = "../activitywatch/aw-core"}
aw_client = {path = "../activitywatch/aw-client"}

[tool.poetry.dev-dependencies]
jupyter = "^1.0.0"
ipykernel = "^5.1.3"
pytest = "^5.3.2"
flake8 = "^3.7.9"
mypy = "^0.761"
jupyterlab = "^1.2.4"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
